# Generated by Django 2.1.7 on 2019-04-16 11:33

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181219_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to=shop.models.image_folder),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
